#ifndef SWP_BANK_ERRNO_H__
#define SWP_BANK_ERRNO_H__

enum BANKERRNO{
  NO_HAVE_BIND_BANK = -801,
  BIND_BANK_CARD_ERROR = -802,
  BANK_CARD_NOT_EXIST = -803,
  UNBIND_BANK_CARD_ERROR = -804,

};

#endif
