//  Copyright (c) 2016-2017 The quotations Authors. All rights reserved.
//  Created on: 2017年1月3日 Author: kerry

#ifndef STAR_CIRCLE_OPERATOR_CODE_H_
#define STAR_CIRCLE_OPERATOR_CODE_H_


#include "net/comm_head.h"


namespace circle_logic {


#define R_GET_ALL_CIRCLE_INFO CIRCLE_TYPE * 1000 + 1
#define S_GET_ALL_CIRCLE_INFO CIRCLE_TYPE * 1000 + 2

#define R_GET_STAR_CIRCLE_INFO CIRCLE_TYPE * 1000 + 3
#define S_GET_STAR_CIRCLE_INFO CIRCLE_TYPE * 1000 + 4

#define R_STAR_ADD_CIRCLE CIRCLE_TYPE * 1000 + 5
#define S_STAR_ADD_CIRCLE CIRCLE_TYPE * 1000 + 6

#define R_STAR_DEL_CIRCLE CIRCLE_TYPE * 1000 + 7
#define S_STAR_DEL_CIRCLE CIRCLE_TYPE * 1000 + 8

#define R_USER_APPROVE_CIRCLE CIRCLE_TYPE * 1000 + 9
#define S_USER_APPROVE_CIRCLE CIRCLE_TYPE * 1000 + 10

#define R_USER_COMMENT_CIRCLE CIRCLE_TYPE * 1000 + 11
#define S_USER_COMMENT_CIRCLE CIRCLE_TYPE * 1000 + 12

#define R_STAR_REPLY_COMMENT CIRCLE_TYPE * 1000 + 13
#define S_STAR_REPLY_COMMENT CIRCLE_TYPE * 1000 + 14


#define R_GET_USER_ASK CIRCLE_TYPE * 1000 + 15 //获取用户问答信息
#define S_GET_USER_ASK CIRCLE_TYPE * 1000 + 16

#define R_GET_STAR_USER_ASK CIRCLE_TYPE * 1000 + 17 //获取指定明星所有用户问答信息
#define S_GET_STAR_USER_ASK CIRCLE_TYPE * 1000 + 18

#define R_USER_ASK CIRCLE_TYPE * 1000 + 19 // 用户提问
#define S_USER_ASK CIRCLE_TYPE * 1000 + 20

#define R_STAR_ANSWER CIRCLE_TYPE * 1000 + 21//明星回答问题
#define S_STAR_ANSWER CIRCLE_TYPE * 1000 + 22

#define R_USER_SEE_VOICE CIRCLE_TYPE * 1000 + 23  //用户查看语音
#define S_USER_SEE_VOICE CIRCLE_TYPE * 1000 + 24

#define R_USER_SEE_VIDEO CIRCLE_TYPE * 1000 + 25  //用户查看视频
#define S_USER_SEE_VIDEO CIRCLE_TYPE * 1000 + 26


#define R_GET_ALLSTAR_USER_ASK_HOT CIRCLE_TYPE * 1000 + 27  //获取明星最热问答
#define S_GET_ALLSTAR_USER_ASK_HOT CIRCLE_TYPE * 1000 + 28

#define R_GET_QINIU_TOKEN CIRCLE_TYPE * 1000 + 29
#define S_GET_QINIU_TOKEN CIRCLE_TYPE * 1000 + 30

#define R_TEST_TEST CIRCLE_TYPE * 1000 + 66
}
#endif 

