#ifndef SWP_MARKET_ERROR_H
#define SWP_MARKET_ERROR_H


enum MARKETERRORNO
{
  NO_HAVE_DATA = -1101,
  NO_GET_MARKET_STAR_TRANSFER = -1102,
  NO_GET_MARKET_STAR_SEEK = -1103,
  NO_ADD_OPTION_STAR = -1104,
  NO_GET_OPTION_STAR_LIST = -1105,
  NO_GET_STAR_ACHIVE = -1106,
  NO_GET_STAR_EXPERIENCE = -1107,
  NO_SEARCH_STAR_LIST = -1108,
  NO_GET_MARKET_STAR_LIST = -1109,
  NO_GET_MARKET_TYPES = -1110
};
#endif
