#ifndef SWP_IMCLOUD_OPERATOR_CODE_H_
#define SWP_IMCLOUD_OPERATOR_CODE_H_


#include "net/comm_head.h"
#include "comm/comm_head.h"


namespace market_logic {
#define R_MARKETTYPES_GET    MARKET_TYPE * 1000 + 1
#define S_MARKETTYPES_GET    MARKET_TYPE * 1000 + 2

#define R_MARKSTARLIST_GET    MARKET_TYPE * 1000 + 3
#define S_MARKSTRRLIST_GET    MARKET_TYPE * 1000 + 4

#define R_MARKSTARBRIEF_GET    MARKET_TYPE * 1000 + 5
#define S_MARKSTARBRIEF_GET    MARKET_TYPE * 1000 + 6

#define R_SEARCHSTAR_INFO    MARKET_TYPE * 1000 + 7
#define S_SEARCHSTAR_INFO    MARKET_TYPE * 1000 + 8

#define R_MARKETSTAREX_GET    MARKET_TYPE * 1000 + 9
#define S_MARKETSTAREX_GET    MARKET_TYPE * 1000 + 10

#define R_MARKETSTARACHIV_GET    MARKET_TYPE * 1000 + 11
#define S_MARKETSTARACHIV_GET    MARKET_TYPE * 1000 + 12

#define R_MARKSTAROPTION_GET    MARKET_TYPE * 1000 + 13
#define S_MARKSTAROPTION_GET    MARKET_TYPE * 1000 + 14

#define R_MARKSTAROPTION_ADD    MARKET_TYPE * 1000 + 15
#define S_MARKSTAROPTION_ADD    MARKET_TYPE * 1000 + 16

#define R_MARKSTARPRICE_GET    MARKET_TYPE * 1000 + 17
#define S_MARKSTARPRICE_GET    MARKET_TYPE * 1000 + 18

#define R_MARKSTARTRANSFER_GET    MARKET_TYPE * 1000 + 19
#define S_MARKSTARTRANSFER_GET    MARKET_TYPE * 1000 + 20

#define R_MARKSTARSEEK_GET    MARKET_TYPE * 1000 + 21
#define S_MARKSTARSEEK_GET    MARKET_TYPE * 1000 + 22
}
#endif